#!/usr/bin/env python3
"""Create reviewer-ready sequencing output tables from the pipeline results.

This script is intentionally conservative: it reports only values that can be
calculated from FASTQ files, DADA2 denoising statistics, and QIIME 2 feature
tables generated by the pipeline.
"""

from __future__ import annotations

import gzip
import io
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd

PROJECT_DIR = Path(__file__).resolve().parents[1]
RAW_DIR = PROJECT_DIR / "data" / "raw_fastq"
FILTERED_DIR = PROJECT_DIR / "data" / "filtered_prinseq"
EXPORTED_DIR = PROJECT_DIR / "results" / "exported"
REPORT_DIR = PROJECT_DIR / "results" / "reviewer_report"
REPORT_DIR.mkdir(parents=True, exist_ok=True)

FEATURE_TABLE = EXPORTED_DIR / "feature_table.tsv"
RAREFIED_TABLE = EXPORTED_DIR / "rarefied_table.tsv"
DENOISING_STATS = EXPORTED_DIR / "denoising_stats" / "stats.tsv"
METADATA = EXPORTED_DIR / "sample-metadata.used.tsv"
RAREFACTION_DEPTH = EXPORTED_DIR / "rarefaction_depth.txt"


def fastq_records(path: Path) -> int:
    opener = gzip.open if path.suffix == ".gz" else open
    with opener(path, "rt", encoding="utf-8", errors="ignore") as handle:
        return sum(1 for _ in handle) // 4


def sample_from_fastq(path: Path) -> str:
    name = path.name
    for suffix in [".fastq.gz", ".fq.gz", ".fastq", ".fq"]:
        if name.endswith(suffix):
            name = name[: -len(suffix)]
    for suffix in ["_1", "_2"]:
        if name.endswith(suffix):
            name = name[: -len(suffix)]
    return name


def count_fastq_dir(directory: Path) -> pd.DataFrame:
    rows = []
    if not directory.exists():
        return pd.DataFrame(columns=["sample-id", "reads"])
    files = []
    for pattern in ["*.fastq.gz", "*.fq.gz", "*.fastq", "*.fq"]:
        files.extend(directory.glob(pattern))
    for path in sorted(files):
        rows.append({"sample-id": sample_from_fastq(path), "reads": fastq_records(path)})
    if not rows:
        return pd.DataFrame(columns=["sample-id", "reads"])
    return pd.DataFrame(rows).groupby("sample-id", as_index=False)["reads"].sum()


def read_biom_tsv(path: Path) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame()
    kept = []
    with path.open() as handle:
        for line in handle:
            if line.startswith("# Constructed"):
                continue
            if line.startswith("#OTU ID"):
                line = line.replace("#OTU ID", "ASV", 1)
            kept.append(line)
    df = pd.read_csv(io.StringIO("".join(kept)), sep="\t")
    if "ASV" not in df.columns:
        df = df.rename(columns={df.columns[0]: "ASV"})
    for col in df.columns[1:]:
        df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(int)
    return df


def sample_counts_from_table(table: pd.DataFrame, prefix: str) -> pd.DataFrame:
    if table.empty:
        return pd.DataFrame(columns=["sample-id", f"{prefix}_reads", f"{prefix}_asvs"])
    rows = []
    for sample in [c for c in table.columns if c != "ASV"]:
        values = table[sample].astype(int)
        rows.append({
            "sample-id": sample,
            f"{prefix}_reads": int(values.sum()),
            f"{prefix}_asvs": int((values > 0).sum()),
        })
    return pd.DataFrame(rows)


def read_metadata() -> pd.DataFrame:
    if not METADATA.exists():
        return pd.DataFrame(columns=["sample-id", "body_site"])
    rows = []
    with METADATA.open() as handle:
        for line in handle:
            if line.strip() and not line.startswith("#"):
                rows.append(line)
    md = pd.read_csv(io.StringIO("".join(rows)), sep="\t", dtype=str).fillna("")
    if "sample-id" not in md.columns:
        md = md.rename(columns={md.columns[0]: "sample-id"})
    if "body_site" not in md.columns:
        md["body_site"] = ""
    return md[["sample-id", "body_site"]].drop_duplicates()


def read_denoising_stats() -> pd.DataFrame:
    if not DENOISING_STATS.exists():
        return pd.DataFrame(columns=["sample-id"])
    df = pd.read_csv(DENOISING_STATS, sep="\t", comment="#")
    if df.empty:
        return pd.DataFrame(columns=["sample-id"])
    first = df.columns[0]
    df = df.rename(columns={first: "sample-id"})
    rename = {}
    for col in df.columns:
        norm = col.strip().lower().replace(" ", "_").replace("-", "_")
        if norm in {"input", "input_reads"}:
            rename[col] = "dada2_input_reads"
        elif norm in {"filtered", "filtered_reads"}:
            rename[col] = "dada2_filtered_reads"
        elif norm in {"denoised", "denoised_reads"}:
            rename[col] = "dada2_denoised_reads"
        elif norm in {"non_chimeric", "nonchimeric", "non_chimeric_reads"}:
            rename[col] = "dada2_non_chimeric_reads"
    df = df.rename(columns=rename)
    for col in df.columns:
        if col != "sample-id":
            df[col] = pd.to_numeric(df[col], errors="ignore")
    return df


def merge_frames(frames: Iterable[pd.DataFrame]) -> pd.DataFrame:
    out = None
    for frame in frames:
        if frame is None or frame.empty:
            continue
        out = frame.copy() if out is None else out.merge(frame, on="sample-id", how="outer")
    return out if out is not None else pd.DataFrame(columns=["sample-id"])


def main() -> None:
    depth = int(RAREFACTION_DEPTH.read_text().strip()) if RAREFACTION_DEPTH.exists() else 7503

    raw = count_fastq_dir(RAW_DIR).rename(columns={"reads": "raw_fastq_reads"})
    prinseq = count_fastq_dir(FILTERED_DIR).rename(columns={"reads": "prinseq_filtered_reads"})
    metadata = read_metadata()
    denoise = read_denoising_stats()
    feature = sample_counts_from_table(read_biom_tsv(FEATURE_TABLE), "non_rarefied_feature_table")
    rarefied = sample_counts_from_table(read_biom_tsv(RAREFIED_TABLE), "rarefied_feature_table")

    summary = merge_frames([metadata, raw, prinseq, denoise, feature, rarefied])
    summary = summary.sort_values(["body_site", "sample-id"], na_position="last")

    if "non_rarefied_feature_table_reads" in summary.columns:
        summary["rarefaction_depth"] = depth
        summary["retained_after_rarefaction_percent"] = (
            summary.get("rarefied_feature_table_reads", np.nan)
            / summary["non_rarefied_feature_table_reads"].replace(0, np.nan)
            * 100
        ).round(2)
        summary["included_in_rarefied_analysis"] = summary.get("rarefied_feature_table_reads", 0).fillna(0) >= depth

    out_tsv = REPORT_DIR / "reviewer_sequencing_summary.tsv"
    summary.to_csv(out_tsv, sep="\t", index=False)

    body = []
    body.append("# Reviewer sequencing report\n")
    body.append("This report was generated automatically from the raw FASTQ counts, PRINSEQ-filtered FASTQ counts, DADA2 denoising statistics, non-rarefied feature table, and rarefied feature table.\n")
    body.append(f"Rarefaction depth used for alpha-diversity analyses: **{depth:,} sequences per sample**.\n")
    body.append("\n## Rarefaction justification\n")
    body.append("Rarefaction was used to normalize sampling depth across samples before diversity estimation. This standardization reduces the influence of unequal library sizes on Shannon diversity and downstream group comparisons, allowing lung and trachea samples to be compared at the same sequencing depth. Samples with fewer reads than the selected depth are excluded by the QIIME 2 core-metrics workflow.\n")
    body.append("\n## Per-sample sequencing summary\n")
    body.append(summary.to_markdown(index=False))
    body.append("\n")
    (REPORT_DIR / "reviewer_sequencing_summary.md").write_text("\n".join(body))

    print(f"Wrote {out_tsv}")
    print(f"Wrote {REPORT_DIR / 'reviewer_sequencing_summary.md'}")


if __name__ == "__main__":
    main()
